### ISSUE TITLE
Set up automatic flake updates

### ISSUE THREAD

**Issue by szg251** [mlabs-haskell/ogmios-nixos#3]
Something similar to this:
https://github.com/mlabs-haskell/plutus-ledger-api-rust/blob/2a9467769b0e82f88509c389a32fbb9a6e44aa23/flake.nix#L77-L87

**Comment by brainrake** [comment]
This repo will be deprecated in favor of https://github.com/mlabs-haskell/cardano.nix which has automatic flake updates enabled.
